CREATE PROCEDURE rm2.sUserDelete
(
    @UserId INT
)
AS
BEGIN
    SET XACT_ABORT ON;
    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
    BEGIN TRAN;

    DELETE FROM rm2.itColRoom WHERE RoomieId = @UserId;
    DELETE FROM rm2.tRoomie WHERE RoomieId = @UserId;
    DELETE FROM rm2.tUser WHERE UserId = @UserId;
    RETURN 0;
END;