CREATE PROC rm2.sInviteDelete
(
	@Code NVARCHAR(12)
)AS
BEGIN 
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
	BEGIN TRAN;

	IF NOT EXISTS(SELECT * FROM rm2.tInvite i WHERE i.Code = @Code)
	BEGIN
		ROLLBACK;
		RETURN 1;
	END;
	
	DELETE FROM rm2.tInvite WHERE Code = @Code;
	COMMIT;
	RETURN 0;
	
END;