CREATE PROC rm2.sTaskUnassignAll
(
	@TaskId INT
)
AS 
BEGIN
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
	BEGIN TRAN;


	IF NOT EXISTS(SELECT * FROM rm2.tiTaskRoom t WHERE t.TaskId = @TaskId)
	BEGIN
		ROLLBACK;
		RETURN 1;
	END;

	DELETE FROM rm2.tiTaskRoom WHERE TaskId = @TaskId;
	COMMIT;
	RETURN 0;
END;